name: Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get


      - name: Build APK (Release)
        run: flutter build apk --release --no-shrink

      - name: Build App Bundle (AAB)
        run: flutter build appbundle --release --no-shrink

- name: Upload APK Artifact
  uses: actions/upload-artifact@v4
  with:
    name: zefirka-voice-remote-apk
    path: build/app/outputs/flutter-apk/app-release.apk
